export enum DatabaseType {
  POSTGRES_LOGICAL = 'POSTGRES_LOGICAL',
  POSTGRES_PHYSICAL = 'POSTGRES_PHYSICAL',
  MYSQL = 'MYSQL',
  MYSQL_PHYSICAL = 'MYSQL_PHYSICAL',
  MARIADB = 'MARIADB',
  MONGODB = 'MONGODB',
}
